name: zest
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  go_router: ^16.0.0
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  drift: ^2.27.0
  flutter_svg: ^2.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  logger: ^2.6.0
  device_info_plus: ^11.5.0
  url_launcher: ^6.3.1
  drift_flutter: ^0.2.4
  injectable: ^2.5.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dio_smart_retry: ^7.0.1
  flutter_animate: ^4.5.2
  responsive_framework: ^1.5.1
  equatable: ^2.0.7
  pedometer: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  freezed: ^3.0.6
  build_runner: ^2.5.4
  drift_dev: ^2.27.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5


flutter_gen:
  output: lib/src/config/gen/
  line_length: 80

  integrations:
    image: true
    flutter_svg: true
    rive: false
    lottie: false

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
