# .github/ISSUE_TEMPLATE/bug_report.yml

name: "🐛 Bug Report"
description: "File a bug report to help us improve the project."
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: dropdown
    id: task-type
    attributes:
      label: Type of Issue
      description: "What type of issue is this?"
      options:
        - "🐞 Bug"
        - "🔥 Performance Issue"
        - "📄 Documentation Issue"
        - "🎨 UI Glitch"
      default: 0
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: "📝 Describe the bug"
      description: "A clear and concise description of what the bug is. What happened? What did you expect to happen?"
      placeholder: "When I tap the login button, the app crashes instead of navigating to the home screen."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "🔁 Steps to Reproduce"
      description: "How can we reproduce the issue? Please provide detailed steps."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: related-feature
    attributes:
      label: "✨ Related Feature or Screen"
      description: "Which feature or screen is affected by this bug?"
      placeholder: "e.g., Login Page, User Profile, Shopping Cart"
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: "👨‍💻 Problematic Code Snippet"
      description: "If you have identified a problematic piece of code, please paste it here. Use Markdown code blocks for formatting."
      placeholder: |
        ```dart
        // Paste your problematic Dart/Flutter code here
        ```
    validations:
      required: false

  - type: checkboxes
    id: affected-platforms
    attributes:
      label: "📱 Affected Platform(s)"
      description: "Which platforms are affected by this bug?"
      options:
        - label: "Android"
        - label: "iOS"
        - label: "Web"
        - label: "Desktop (Windows/macOS/Linux)"

  - type: textarea
    id: flutter-doctor
    attributes:
      label: "🩺 Flutter Doctor Output"
      description: "Please run `flutter doctor -v` in your terminal and paste the complete output here."
      render: shell
      placeholder: "Paste the output of `flutter doctor -v` here"
    validations:
      required: true