# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: "❓ Ask a Question"
    url: "https://github.com/hamidjalili59/zest/discussions"
    about: "Please ask and answer questions here."